### ISSUE TITLE
Skip invetntory recheck and benchmarks on every Agent start

### ISSUE THREAD

**Issue by J-Run** [zzzteph/kraker#13]
Every time when agent started inventory update and performance benchmarks are performed. 
Unfortunately it takes **a lot of time** on large wordlists, and a benckmark for all types of hashes also not a fast task.

And if set of wordlists and hardware config is stay unchanged theese time-consumpting stages can be skipped.
Optional - add a force inventory rebuild / benchmark buttons to web panel (on agent managment page)

**Comment by zzzteph** [comment]
@J-Run I'm not sure about inventory cause the agent should rebuild statistics only for new or changed wordlists. Same for the benchmark - it should run only at the first start and only if brute force did not trigger the specific hash type for 12 hours.  Does the agent rebuild inventory/perform benchmark each time after restart?

**Comment by zzzteph** [comment]
Yep, a bug exists.

**Comment by narutyona** [comment]
It's not a bug, it's a feature 
![изображение](https://user-images.githubusercontent.com/41623573/132105851-41e33482-aa48-4fbd-afeb-2282ac7171a5.png)

The agent was planned as a never-dying part.  The case with a restart was considered as something that should not happen.
We replaced the hashing function with murmurhash

**Comment by zzzteph** [comment]
New version in https://github.com/zzzteph/kraker/pull/16
