### ISSUE TITLE
broken hashes counter in hashlist 

### ISSUE THREAD

**Issue by J-Run** [zzzteph/kraker#21]
It looks like a `hashcat --left` routine starts before a hashlist is properly flushed on a disk or kind of so. 
In result hashcat calculates a wrong count of hashes to proceed.

steps to reproduce:
1) create a new hashlist of 50 strings of md5's
2) wait for it change status from `todo`
3) check a total hashes counter

**Comment by zzzteph** [comment]
#41c907e1bdb3b3066faa63488313424c86e48fe9

**Comment by zzzteph** [comment]
#https://github.com/zzzteph/kraker/commit/41c907e1bdb3b3066faa63488313424c86e48fe9

**Comment by zzzteph** [comment]
![image](https://user-images.githubusercontent.com/917422/132751686-0f577e10-3ef5-4225-a629-069cbc280e1e.png)

**Comment by zzzteph** [comment]
https://github.com/zzzteph/kraker/releases/tag/v.1.2.1
