### ISSUE TITLE
Human friendly agent names on agents view

### ISSUE THREAD

**Issue by J-Run** [zzzteph/kraker#9]
Currently agents on a agent view, inventory and tasks are indentified by uuid4. It would be nice to see something more human-readable, hostname or any other kind of name

**Comment by zzzteph** [comment]
Maybe some kind of Ubuntu-like naming: **adjective noun**
Like:

- Hardy Heron
- Darkest Moria

**Comment by J-Run** [comment]
when we serving several agents on a diffenernt hosts idetnifying each of them is very important for troubleshooting. So hostname fits fine here

**Comment by J-Run** [comment]
Inventory and tasks views are still have a uuid4 naming for agents
